# Generated by Django 5.0.6 on 2024-06-19 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BasketItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("itemCount", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Basket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("items", models.ManyToManyField(to="menu.basketitem")),
            ],
        ),
        migrations.CreateModel(
            name="Dish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "spicy",
                    models.IntegerField(
                        choices=[
                            (0, "Not Spicy"),
                            (1, "Mild"),
                            (2, "Medium"),
                            (3, "Spicy"),
                            (4, "Very Spicy"),
                        ]
                    ),
                ),
                ("withNut", models.BooleanField()),
                ("isVegetarian", models.BooleanField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("imageUrl", models.URLField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dishes",
                        to="menu.category",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="basketitem",
            name="dish",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="menu.dish"
            ),
        ),
    ]
